<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * hook_help()
 */
function interfon_data_import_help($route_name, RouteMatchInterface $route_match) {
    switch($route_name) {
        // Main module help for the custom_user_migrate module
        case 'help.page.interfon_data_import':
            $output='<h3>'.t('About').'</h3>'
                .'<p>'.t('Interfon Data import').'</p>';
    }
}

/**
 * hook_migration_plugins_alter()
 */
function interfon_data_import_migration_plugins_alter(&$definitions) {
    $module_path=drupal_get_path('module','interfon_data_import');
    $entities=[
        'interfon_committee',
        'interfon_committee_en',
        // 'interfon_salutation',
        // 'interfon_salutation_en',
        'interfon_user',
        ];
    foreach ($entities as $entity) {
        $definitions[$entity]['source']['path']=
            $module_path . $definitions[$entity]['source']['path'];
        error_log($entity.".source.path=".$definitions[$entity]['source']['path']);
    }
}
