<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * hook_help()
 */
function interfon_data_import_help($route_name, RouteMatchInterface $route_match) {
    switch($route_name) {
        // Main module help for the custom_user_migrate module
        case 'help.page.interfon_data_import':
            $output='<h3>'.t('About').'</h3>'
                .'<p>'.t('Data import').'</p>';
    }
}

/**
 * hook_migration_plugins_alter()
 */
function interfon_data_import_migration_plugins_alter(&$definitions) {
    $definitions['interfon_committee']['source']['path']=
        drupal_get_path('module','interfon_data_import')
        .$definitions['interfon_committee']['source']['path'];

    $definitions['interfon_user']['source']['path']=
        drupal_get_path('module','interfon_data_import')
        .$definitions['interfon_user']['source']['path'];
}